---
language: "python"
python:
  - "3.6"
addons:
  apt:
    packages:
      - oracle-java8-set-default  # Java8 is required by html5validator
install:
  - pip install yamllint html5validator
script:
  - yamllint journeys.yaml
  - html5validator --show-warnings --root .
