# Setup
tagline:      All the links you'll ever need for journey docs
baseurl:      ""
paginate:     1

# About/contact
author:
  url:        https://github.com/stevemart/journey-data

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
